program Noil_ControlMedico_19;


uses
  Forms,
  frm_connection in '..\verificar\frm_connection.pas' {connection: TDataModule},
  global in '..\verificar\global.pas',
  frm_setup in '..\verificar\frm_setup.pas' {frmSetup},
  frm_barra in '..\verificar\frm_barra.pas' {frmBarra: TFrame},
  frm_turnos in '..\verificar\frm_turnos.pas' {frmTurnos},
  Utilerias in '..\verificar\Utilerias.pas',
  frm_gruposxprograma in '..\verificar\frm_gruposxprograma.pas' {frmGruposxPrograma},
  frm_GruposUsuarios in '..\verificar\frm_GruposUsuarios.pas' {frmGrupos},
  frm_activos in '..\verificar\frm_activos.pas' {frmActivos},
  frm_programas in '..\verificar\frm_programas.pas' {frmProgramas},
  frm_Kardex in '..\verificar\frm_Kardex.pas' {frmKardex},
  frm_acceso in '..\verificar\frm_acceso.pas' {frmacceso},
  frm_firmantes in '..\verificar\frm_firmantes.pas' {frmFirmas},
  frm_usuarios in '..\verificar\frm_usuarios.pas' {frmUsuarios},
  frm_residencias in '..\verificar\frm_residencias.pas' {frmResidencias},
  frm_seleccion2 in '..\verificar\frm_seleccion2.pas' {frmSeleccion2},
  frm_contratos in '..\verificar\frm_contratos.pas' {frmContratos},
  StoHtmlHelp in '..\verificar\StoHtmlHelp.pas',
  frm_Modulosxusuario in '..\verificar\frm_Modulosxusuario.pas' {frmModulosxUsuario},
  Unit_Barras in '..\verificar\Unit_Barras.pas',
  UnitExcel in '..\verificar\UnitExcel.pas',
  UTChartMarco in '..\verificar\UTChartMarco.pas',
  UTChartMouse in '..\verificar\UTChartMouse.pas',
  masUtilerias in '..\verificar\masUtilerias.pas',
  UFunctionsGHH in '..\verificar\UFunctionsGHH.pas',
  unitmanejofondo in '..\verificar\unitmanejofondo.pas',
  UnitValidaTexto in '..\verificar\UnitValidaTexto.pas',
  unitActivaPop in '..\verificar\unitActivaPop.pas',
  UnitGenerales in '..\verificar\UnitGenerales.pas',
  UnitTablasImpactadas in '..\verificar\UnitTablasImpactadas.pas',
  UnitTBotonesPermisos in '..\verificar\UnitTBotonesPermisos.pas' {,
  FrmMovtoPersonalxoficio in 'FrmMovtoPersonalxoficio.pas' {FrmMovtosPersonalxoficio},
  frm_NuevoIdioma in '..\verificar\frm_NuevoIdioma.pas' {frmNuevoIdioma},
  frm_nuc_Organizacion in '..\verificar\frm_nuc_Organizacion.pas' {frm_nucOrganizacion},
  AcroPDFLib_TLB in '..\verificar\AcroPDFLib_TLB.pas',
  frm_repositorio in '..\verificar\frm_repositorio.pas' {frmrepositorio: TDataModule},
  Func_Genericas in '..\verificar\Func_Genericas.pas',
  UnitMetodos in '..\verificar\UnitMetodos.pas',
  UTFrmDepartamentos in '..\verificar\UTFrmDepartamentos.pas' {FrmDepartamentos},
  UFrmEnviarCorreo in '..\verificar\UFrmEnviarCorreo.pas' {FrmEnviarCorreo},
  Frm_PopUpImportacionPP in '..\verificar\Frm_PopUpImportacionPP.pas' {FrmPopUpImportacionPP},
  ExportaExcel in '..\verificar\ExportaExcel.pas',
  frm_Almacenes in '..\verificar\Modulos\Flujo Materiales\frm_Almacenes.pas' {frmAlmacenes},
  frm_almacenesporcontrato in '..\verificar\Modulos\Flujo Materiales\frm_almacenesporcontrato.pas' {frmAlmacenesPorContrato},
  frm_almacenesporusuario in '..\verificar\Modulos\Flujo Materiales\frm_almacenesporusuario.pas' {frmAlmacenesPorUsuario},
  frm_SetupAlm in '..\verificar\Modulos\Flujo Materiales\frm_SetupAlm.pas' {frmSetupAlm},
  frm_TipoMovto in '..\verificar\Modulos\Flujo Materiales\frm_TipoMovto.pas' {frmMovtos},
  frm_embarcaciones in '..\verificar\Modulos\Renta Diaria\frm_embarcaciones.pas' {frmEmbarcaciones},
  Frm_ImportaExportaActiv in '..\verificar\Modulos\Renta Diaria\Frm_ImportaExportaActiv.pas' {FrmImportaExportaActiv},
  unt_Actividades in '..\verificar\Modulos\Renta Diaria\unt_Actividades.pas',
  UnitTarifa in '..\verificar\Modulos\Renta Diaria\UnitTarifa.pas',
  frm_ReportePeriodo in '..\verificar\Modulos\Renta Diaria\frm_ReportePeriodo.pas' {frmReportePeriodo},
  frm_plataformas in '..\verificar\frm_plataformas.pas' {frmPlataformas},
  frm_proveedores in '..\verificar\Modulos\Flujo Materiales\frm_proveedores.pas' {frmProveedores},
  frm_Pernoctan in '..\verificar\frm_Pernoctan.pas' {frmPernoctan},
  frm_contratosxusuario in '..\verificar\frm_contratosxusuario.pas' {frmContratosxUsuario},
  frm_barraH1 in '..\verificar\frm_barraH1.pas' {frmBarraH1: TFrame},
  frm_barraH2 in '..\verificar\frm_barraH2.pas' {frmBarraH2: TFrame},
  frm_Empresas in '..\verificar\frm_Empresas.pas' {frm_Empresa},
  frm_deptos in '..\verificar\frm_deptos.pas' {frmDeptos},
  frm_catalogos_almacen in '..\verificar\Modulos\Flujo Materiales\frm_catalogos_almacen.pas' {frmCatalogosAlmacen},
  frm_evaluacion in '..\verificar\Modulos\Flujo Materiales\frm_evaluacion.pas' {frmEvaluacion},
  Ufrm_Loading in '..\verificar\Ufrm_Loading.pas' {frm_Loading},
  UnitRH in '..\verificar\Modulos\Recursos Humanos\UnitRH.pas',
  frm_materiales in '..\verificar\Modulos\Flujo Materiales\frm_materiales.pas' {frmMateriales},
  Form_Esperando in '..\verificar\Form_Esperando.pas' {FormEsperando},
  UFrmNotificaciones in '..\verificar\Modulos\Flujo Materiales\UFrmNotificaciones.pas' {FrmNotificaciones},
  DebenuPDFLibraryAX0912_TLB in '..\verificar\2007-DebenuPDFLibrary\DebenuPDFLibraryAX0912_TLB.pas',
  frm_VerPDF in '..\verificar\frm_VerPDF.pas' {frmVerPDF},
  UFrm_EvaluaProveedor in '..\verificar\Modulos\Flujo Materiales\UFrm_EvaluaProveedor.pas' {Frm_EvaluaProveedor},
  Frm_RequisicionMaterial in '..\verificar\Modulos\Flujo Materiales\Frm_RequisicionMaterial.pas' {FrmRequisicionMaterial},
  UnitReportes in '..\verificar\UnitReportes.pas',
  frm_reportesRH in '..\verificar\Modulos\Recursos Humanos\frm_reportesRH.pas' {frmReportesRH},
  frm_SeguimientoReq in '..\verificar\Modulos\Flujo Materiales\frm_SeguimientoReq.pas' {frmSeguimientoReq},
  frm_Noil_SS7 in '..\verificar\frm_Noil_SS7.pas' {frmNoil_SS7},
  frm_agregar_masivo in '..\verificar\Modulos\Recursos Humanos\frm_agregar_masivo.pas' {frmAgregarMasivo},
  frm_Documentos_Reportes in '..\verificar\Modulos\Recursos Humanos\frm_Documentos_Reportes.pas' {FrmDocumentos_Reportes},
  frm_agregar_masivoOP in '..\verificar\Modulos\Operaciones\frm_agregar_masivoOP.pas' {frmAgregarMasivoOP},
  Frm_Asignacion in '..\verificar\Modulos\Flujo Materiales\Frm_Asignacion.pas' {FrmAsignacion},
  frm_catalogos_Operaciones in '..\verificar\Modulos\Operaciones\frm_catalogos_Operaciones.pas' {frmCatalogosOperacion},
  Frm_CostoAlmacen in '..\verificar\Modulos\Flujo Materiales\Frm_CostoAlmacen.pas' {FrmCostoAlmacen},
  frm_ReporteControl in '..\verificar\Modulos\Recursos Humanos\frm_ReporteControl.pas' {FrmReporteControl},
  frm_rptEvaluaProv in '..\verificar\Modulos\Flujo Materiales\frm_rptEvaluaProv.pas' {frmRptEvaluacionProv},
  Frm_CotizacionP in '..\verificar\Modulos\Flujo Materiales\Frm_CotizacionP.pas' {FrmCotizacionesP},
  frm_Proyectos in '..\verificar\Modulos\Operaciones\frm_Proyectos.pas' {frmProyectos},
  frm_clientes in '..\verificar\Modulos\Gerencia Administrativa\frm_clientes.pas' {frmClientes},
  frm_folios in '..\verificar\frm_folios.pas' {frmFolios},
  Frm_Comentarios in '..\verificar\Frm_Comentarios.pas' {FrmComentarios},
  frm_Presupuesto in '..\verificar\Modulos\Operaciones\frm_Presupuesto.pas' {frmPresupuesto},
  Frm_CostoPresupuesto in '..\verificar\Modulos\Operaciones\Frm_CostoPresupuesto.pas' {frmCostoPresupuesto},
  frm_usuarios_proyectos in '..\verificar\frm_usuarios_proyectos.pas' {frmUsuariosXproyectos},
  frm_importaciondedatos in '..\verificar\frm_importaciondedatos.pas' {frmImportaciondeDatos},
  frm_Pedidos in '..\verificar\Modulos\Flujo Materiales\frm_Pedidos.pas' {frmPedidos},
  frm_FirmasNota in '..\verificar\frm_FirmasNota.pas' {frmFirmasNota},
  Frm_Modal in '..\verificar\Frm_Modal.pas' {FrmModal},
  frm_cotizacionCMMI in '..\verificar\Modulos\Flujo Materiales\frm_cotizacionCMMI.pas' {frmCotizacionCMMI},
  frm_CentroCosto in '..\verificar\Modulos\Flujo Materiales\frm_CentroCosto.pas' {frmCentroCosto},
  frm_AprobacionPagos in '..\verificar\Modulos\Flujo Materiales\frm_AprobacionPagos.pas' {frmAprobacionP},
  frm_ApruebaRequisiciones in '..\verificar\Modulos\Flujo Materiales\frm_ApruebaRequisiciones.pas' {frmApruebaRequisiciones},
  Frm_RequerimientosControlCalidad in '..\verificar\Modulos\Flujo Materiales\Frm_RequerimientosControlCalidad.pas' {FrmRequerimientosControlCalidad},
  frm_Concentrado_InspeccionMat in '..\verificar\Modulos\Flujo Materiales\frm_Concentrado_InspeccionMat.pas' {FrmConcentrado_InspeccionMat},
  frm_agregar_OrdenCompra in '..\verificar\Modulos\Flujo Materiales\frm_agregar_OrdenCompra.pas' {frmAgregarMasivoOrdenCompra},
  frm_Planta in '..\verificar\Modulos\Flujo Materiales\frm_Planta.pas' {frmPlanta},
  frm_CargaMaterial in '..\verificar\Modulos\Flujo Materiales\frm_CargaMaterial.pas' {frmInspecciónMaterialDetalle},
  frm_GerentesPorDepartamento in '..\verificar\Modulos\frm_GerentesPorDepartamento.pas' {frmGerentesPorDepartamento},
  frm_Compradores in '..\verificar\Modulos\frm_Compradores.pas' {frmCompradores},
  frm_requisicion_ss7 in '..\verificar\Modulos\Flujo Materiales\frm_requisicion_ss7.pas' {FrmRequisicionss7},
  frm_agregar_Requisicion in '..\verificar\Modulos\Flujo Materiales\frm_agregar_Requisicion.pas' {frmAgregarMasivoRequisicion},
  UFrmIndicadores in '..\verificar\Modulos\Flujo Materiales\UFrmIndicadores.pas' {FrmIndicadores},
  frm_GridFM in '..\verificar\Modulos\Flujo Materiales\frm_GridFM.pas' {frmGridFM},
  frm_Pedidos_SAP_Estatus in '..\verificar\Modulos\Flujo Materiales\frm_Pedidos_SAP_Estatus.pas' {frmPedidos_SAP_Estatus},
  frm_InspeccionMateriales in '..\verificar\Modulos\Flujo Materiales\frm_InspeccionMateriales.pas' {FrmInspeccionMateriales},
  Frm_BancosMovimientos in '..\verificar\Modulos\Gerencia Administrativa\Frm_BancosMovimientos.pas' {frmBancosMovimientos},
  frm_Buscar in '..\verificar\Modulos\Presupuesto\frm_Buscar.pas' {frmBuscar},
  frm_ContratoReq in '..\verificar\Modulos\Flujo Materiales\frm_ContratoReq.pas' {frmContratoReq},
  frm_OrdenTrabajo in '..\verificar\Modulos\Operaciones\frm_OrdenTrabajo.pas' {frmOrdenTrabajo},
  frm_almacenamiento in '..\verificar\Modulos\Flujo Materiales\frm_almacenamiento.pas' {frmAlmacenamiento},
  frm_catalogo_empleados in '..\verificar\Modulos\Recursos Humanos\frm_catalogo_empleados.pas' {frmCatalogoEmpleados},
  frm_salarios in '..\verificar\Modulos\Recursos Humanos\frm_salarios.pas' {frmSalarios},
  frm_rangoSalarios in '..\verificar\Modulos\Recursos Humanos\frm_rangoSalarios.pas' {frmRangoSalarios},
  frm_Catalogos_rh_tipos in '..\verificar\Modulos\Recursos Humanos\frm_Catalogos_rh_tipos.pas' {frmCatalogosRHTipos},
  frm_tipos_nomina in '..\verificar\Modulos\Recursos Humanos\frm_tipos_nomina.pas' {frmTiposNomina},
  frm_guardias in '..\verificar\Modulos\Recursos Humanos\frm_guardias.pas' {FrmGuardias},
  Frm_ConfGuardias in '..\verificar\Modulos\Recursos Humanos\Frm_ConfGuardias.pas' {FrmConfGuardias},
  frm_bajar_masivo in '..\verificar\Modulos\Recursos Humanos\frm_bajar_masivo.pas' {frmBajarMasivo},
  frm_contratar_masivo in '..\verificar\Modulos\Recursos Humanos\frm_contratar_masivo.pas' {frmContratarMasivo},
  frm_controlComisiones in '..\verificar\Modulos\Recursos Humanos\frm_controlComisiones.pas' {frmControlComision},
  Frm_PreNomina in '..\verificar\Modulos\Recursos Humanos\Frm_PreNomina.pas' {FrmPreNomina},
  frm_comentarios_nomina in '..\verificar\Modulos\Recursos Humanos\frm_comentarios_nomina.pas' {frmComentariosNomina},
  Frm_Nomina in '..\verificar\Modulos\Recursos Humanos\Frm_Nomina.pas' {FrmNomina},
  frm_CatalogoNominas in '..\verificar\Modulos\Recursos Humanos\frm_CatalogoNominas.pas' {FrmCatalogoNominas},
  frm_personal_prov in '..\verificar\Modulos\Recursos Humanos\frm_personal_prov.pas' {frmPersonalProv},
  frm_EvaluaCompetencias in '..\verificar\Modulos\Recursos Humanos\frm_EvaluaCompetencias.pas' {frm_EvaluaCompetencias},
  Frm_Justificar in '..\verificar\Modulos\Recursos Humanos\Frm_Justificar.pas' {FrmJustificar},
  Frm_Asignar_Guardias in '..\verificar\Modulos\Recursos Humanos\Frm_Asignar_Guardias.pas' {FrmAsignarGuardias},
  frm_diaslaboradosSIANI in '..\verificar\Modulos\Recursos Humanos\frm_diaslaboradosSIANI.pas' {frmDiasLaboradosSIANI},
  frm_SeguroVida in '..\verificar\Modulos\Recursos Humanos\frm_SeguroVida.pas' {FrmSeguroVida},
  frm_abrereporte in '..\verificar\frm_abrereporte.pas' {frmAbreReporte_},
  frm_Existencia in '..\verificar\Modulos\Flujo Materiales\frm_Existencia.pas' {frmExistencia},
  frm_MaterialesPO in '..\verificar\Modulos\Flujo Materiales\frm_MaterialesPO.pas' {FrmMaterialesPO},
  frm_AvisoEmbarque in '..\verificar\Modulos\Flujo Materiales\frm_AvisoEmbarque.pas' {frmAvisoEmbarque},
  Frm_SolicitudMaterial in '..\verificar\Modulos\Flujo Materiales\Frm_SolicitudMaterial.pas' {FrmSolicitudMaterial},
  frm_Transito in '..\verificar\Modulos\Flujo Materiales\frm_Transito.pas' {frmTransito},
  frm_ComprobantesFiscalesD in '..\verificar\Modulos\Gerencia Administrativa\frm_ComprobantesFiscalesD.pas' {frmComprobantesFiscalesD},
  frm_VisualizaComprobanteFD in '..\verificar\Modulos\Gerencia Administrativa\frm_VisualizaComprobanteFD.pas' {frmVisualizaComprobanteFD},
  frm_SolicitudDeMateriales in '..\verificar\Modulos\Flujo Materiales\frm_SolicitudDeMateriales.pas' {frmSolicitudDeMateriales},
  UFrm_EvaluaProveedorCMMI in '..\verificar\Modulos\Flujo Materiales\UFrm_EvaluaProveedorCMMI.pas' {Frm_EvaluaProveedorCMMI},
  frm_Pedidos_SAP in '..\verificar\Modulos\Flujo Materiales\frm_Pedidos_SAP.pas' {frmPedidos_SAP},
  frm_VerDetalle_MR in '..\verificar\Modulos\Flujo Materiales\frm_VerDetalle_MR.pas' {frmVerDetalleMR},
  frm_configuraMail_mensajes in '..\verificar\frm_configuraMail_mensajes.pas' {frmConfiguraMail_mensajes},
  frm_Estatus_POEntradas in '..\verificar\Modulos\Flujo Materiales\frm_Estatus_POEntradas.pas' {frmEstatus_POEntradas},
  frm_AvisoEmbarque_THY in '..\verificar\Modulos\Flujo Materiales\frm_AvisoEmbarque_THY.pas' {frmAvisoEmbarque_THY},
  frm_EntradaAlmacen_THY in '..\verificar\Modulos\Flujo Materiales\frm_EntradaAlmacen_THY.pas' {frmEntradaAlmacen_THY},
  frm_SalidaAlmacen_THY in '..\verificar\Modulos\Flujo Materiales\frm_SalidaAlmacen_THY.pas' {frmSalidaAlmacen_THY},
  frm_agregar_masivoOP_THY in '..\verificar\Modulos\Operaciones\frm_agregar_masivoOP_THY.pas' {frmAgregarMasivoOP_THY},
  frm_materiales_SS7 in '..\verificar\Modulos\Flujo Materiales\frm_materiales_SS7.pas' {frmMateriales_SS7},
  frm_EntradaAlmacen_SS7 in '..\verificar\Modulos\Flujo Materiales\frm_EntradaAlmacen_SS7.pas' {frmEntradaAlmacen_SS7},
  frm_EntradaAlmacen in '..\verificar\Modulos\Flujo Materiales\frm_EntradaAlmacen.pas' {frmEntradaAlmacen},
  frm_agregar_masivoOP_SS7 in '..\verificar\Modulos\Operaciones\frm_agregar_masivoOP_SS7.pas' {frmAgregarMasivoOP_SS7},
  frm_SalidaAlmacen in '..\verificar\Modulos\Flujo Materiales\frm_SalidaAlmacen.pas' {frmSalidaAlmacen},
  frm_SalidaAlmacen_SS7 in '..\verificar\Modulos\Flujo Materiales\frm_SalidaAlmacen_SS7.pas' {frmSalidaAlmacen_SS7},
  frm_RevisionesRequisicion in '..\verificar\Modulos\Flujo Materiales\frm_RevisionesRequisicion.pas' {FrmRevisionesRequisiciones},
  frm_VerificarSs7 in '..\verificar\Modulos\Recursos Humanos\frm_VerificarSs7.pas' {FrmVerificarSs7},
  FrmAsistenciaMedica in '..\verificar\Modulos\Recursos Humanos\FrmAsistenciaMedica.pas' {FrmAsistenciaMed},
  frm_verificar in '..\verificar\Modulos\Recursos Humanos\frm_verificar.pas' {FrmVerificar},
  frm_valida in '..\verificar\frm_valida.pas' {frmValida},
  frm_valida_ss7 in '..\verificar\frm_valida_ss7.pas' {frmValida_ss7},
  frm_agregar_servicios in '..\verificar\Modulos\Flujo Materiales\frm_agregar_servicios.pas' {frmAgregarMasivoServicios},
  frm_abrereporte_ss7 in '..\verificar\frm_abrereporte_ss7.pas' {frmAbreReporte_ss7},
  frm_agregar_Accesorios in '..\verificar\Modulos\Flujo Materiales\frm_agregar_Accesorios.pas' {frmAgregarMasivoAccesorios},
  frm_EntregaEquipo in '..\verificar\Modulos\Control EPP\frm_EntregaEquipo.pas' {frmEntregaEquipo},
  frm_materiales_CMMI in '..\verificar\Modulos\Flujo Materiales\frm_materiales_CMMI.pas' {frmMateriales_CMMI},
  frm_servicios_CMMI in '..\verificar\Modulos\Flujo Materiales\frm_servicios_CMMI.pas' {frmServicios_CMMI},
  frm_DevolucionEquipo in '..\verificar\Modulos\Control EPP\frm_DevolucionEquipo.pas' {frmDevolucionEquipo},
  frm_CuentasPorPagar in '..\verificar\Modulos\Gerencia Administrativa\frm_CuentasPorPagar.pas' {frmCuentasPorPagar},
  frm_AsistenciaPersonal in '..\verificar\Modulos\Recursos Humanos\frm_AsistenciaPersonal.pas' {FrmAsistenciaPersonal},
  frm_agregar_personal in '..\verificar\Modulos\Recursos Humanos\frm_agregar_personal.pas' {frmAgregarPersonal},
  Frm_ConfBiometrico in '..\verificar\Frm_ConfBiometrico.pas' {FrmConfBiometrico};

{$R *.TLB}

{$R *.res}

begin
  Application.Initialize;
  Application.Title := 'Sistema Noil Empresarial';
  Application.HelpFile := '';
  Application.CreateForm(Tconnection, connection);
  Application.CreateForm(TfrmNoil_SS7, frmNoil_SS7);
  Application.CreateForm(Tfrmacceso, frmacceso);
  Application.CreateForm(TfrmSeleccion2, frmSeleccion2);
  Application.CreateForm(Tfrmrepositorio, frmrepositorio);
  Application.CreateForm(Tfrm_Loading, frm_Loading);
  Application.CreateForm(TFormEsperando, FormEsperando);
  Application.Run;
end.




